### ISSUE TITLE
Conflict between darkness and JustEnoughIDs (Mixins cannot be accessed?)

### ISSUE THREAD

**Issue by sanedsf** [yamporg/darkness#1]
### What version are you using?

I’m using darkness-0.2.1-all.jar from CurseForge.
The latest forge for 1.12.2 forge-14.23.5.2847 from Twitch Client.

### Does this issue reproduce with the latest release?

Yes it does.

### Which mods do you have installed?

darkness-0.2.1-all.jar
JustEnoughIDs-1.0.3-48.jar [https://www.curseforge.com/minecraft/mc-mods/jeid](https://www.curseforge.com/minecraft/mc-mods/jeid)

### What did you do?

Installing JustEnoughIDs will break the mod straight up. JustEnoughIDs is changing the way the Mixers are loaded from forge. That's why when you are trying to load them; it throws this error.

This is the error message (pastebin URL):
https://pastebin.com/kWDc0pP2

Is it a JustEnoughIDs bug as well, can it be solved only at your end, or nothing can be done about it in general?

**Comment by tie** [comment]
The issue is caused by both darkness and JustEnoughIDs embedding different versions of [Mixin library](https://github.com/SpongePowered/Mixin). Notoriously, darkness embeds the latest release `0.8.1` which is incompatible with what JEID targets `0.7.11`. However, darkness should work just fine with older releases, though I am not sure what is the exact minimum required version.

That said, the first option is to rename `darkness-0.2.1-all.jar` to something like `zzz-darkness-0.2.1-all.jar`. That way Forge would use Mixin library from JEID (it appears that mods are loaded in lexicographical order).

Another (better) option is to use [jar file without `all` suffix](https://www.curseforge.com/minecraft/mc-mods/dynamic-darkness/files/2884543). This one does not embed Mixins and expects some other mod or library to ship it. Unfortunately, CurseForge displays only one file per Minecraft release so it is not easily discoverable. I’ve updated CurseForge description page with info about this file and issue.

**Comment by tie** [comment]
I’ll address this issue further by downgrading the embed Mixin version to 0.7.11 in the next release. And probably bump it back to 0.8.x after updating for 1.14.x.

**Comment by sanedsf** [comment]
This happened a couple hours ago.
https://github.com/DimensionalDevelopment/JustEnoughIDs/pull/117#issue-390025562
Essentially Mixin was updated to 0.8 for JEID.

The -all version works now with the latest JEID (1.0.3-54). Have not seen any issues so far.
